"""empty message

Revision ID: 007f6d9c59c7
Revises: df617bcfb09c
Create Date: 2021-09-03 19:01:46.182272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007f6d9c59c7'
down_revision = 'df617bcfb09c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Trang', sa.Column('thumbnail', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Trang', 'thumbnail')
    # ### end Alembic commands ###
