"""empty message

Revision ID: 0780fe889571
Revises: 007f6d9c59c7
Create Date: 2021-09-04 21:29:32.926897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0780fe889571'
down_revision = '007f6d9c59c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code', 'password')
    # ### end Alembic commands ###
