"""empty message

Revision ID: 08a6ae3f01a9
Revises: d8266fa0a9c3
Create Date: 2021-08-21 10:04:57.725232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a6ae3f01a9'
down_revision = 'd8266fa0a9c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'username')
    op.drop_column('post', 'comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('comments', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
