"""empty message

Revision ID: 15f079ae09b4
Revises: 
Create Date: 2021-08-20 15:51:31.840384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f079ae09b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('name2', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'role', ['name2'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role', type_='unique')
    op.drop_column('role', 'name2')
    # ### end Alembic commands ###
