"""empty message

Revision ID: 4ffd9b27cb0e
Revises: a15bf48b824e
Create Date: 2021-08-28 21:33:28.543462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ffd9b27cb0e'
down_revision = 'a15bf48b824e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code', sa.Column('views', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code', 'views')
    # ### end Alembic commands ###
