"""empty message

Revision ID: a15bf48b824e
Revises: f6121fd8428f
Create Date: 2021-08-25 14:19:48.727799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a15bf48b824e'
down_revision = 'f6121fd8428f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_syntax',
    sa.Column('syntax_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('syntax_id'),
    sa.UniqueConstraint('name')
    )
    op.alter_column('category', 'slug',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.add_column('code', sa.Column('title', sa.String(length=200), nullable=False))
    op.add_column('code', sa.Column('slug', sa.String(length=300), nullable=False))
    op.add_column('code', sa.Column('syntax_id', sa.Integer(), nullable=True))
    op.add_column('code', sa.Column('description', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'code', ['slug'])
    op.create_foreign_key(None, 'code', 'code_syntax', ['syntax_id'], ['syntax_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'code', type_='foreignkey')
    op.drop_constraint(None, 'code', type_='unique')
    op.drop_column('code', 'description')
    op.drop_column('code', 'syntax_id')
    op.drop_column('code', 'slug')
    op.drop_column('code', 'title')
    op.alter_column('category', 'slug',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_table('code_syntax')
    # ### end Alembic commands ###
