"""empty message

Revision ID: a94374dd7b92
Revises: ade92f89d203
Create Date: 2021-08-21 10:42:46.460247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a94374dd7b92'
down_revision = 'ade92f89d203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'name2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('name2', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
