"""empty message

Revision ID: ade92f89d203
Revises: 08a6ae3f01a9
Create Date: 2021-08-21 10:35:41.295525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade92f89d203'
down_revision = '08a6ae3f01a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('name2', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'name2')
    # ### end Alembic commands ###
