"""empty message

Revision ID: f6121fd8428f
Revises: a94374dd7b92
Create Date: 2021-08-24 18:53:22.917552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6121fd8428f'
down_revision = 'a94374dd7b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('slug', sa.String(length=200)))
    op.create_unique_constraint(None, 'category', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_column('category', 'slug')
    # ### end Alembic commands ###
